apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.quizItService.user.db.service.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.quizItService.user.db.label }}
  ports:
    - protocol: TCP
      port: 27017