apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Chart.Name}}-{{.Values.quizItService.user.name}}-db
spec:
  serviceName: {{ .Values.quizItService.user.db.label }}
  replicas: {{ .Values.quizItService.user.db.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.quizItService.user.db.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.quizItService.user.db.label }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:6.0.9-rc1
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: quizit-user-db
            mountPath: /data/db
      # volumes:
      # - name: quizit-user-db
      #   persistentVolumeClaim:
      #     claimName: quizit-user-prod-pvc
  # volumeClaimTemplates:
  # - metadata:
  #     name: quizit-user-prod-pvc
  #   spec:
  #     storageClassName: {{ .Values.quizItService.user.db.storage.className }}
  #     accessModes: 
  #       - {{ .Values.storage.accessMode }}
  #     resources:
  #       requests:
  #         storage: {{ .Values.quizItService.user.db.storage.request }}