# Default dev-values for quizit.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: dev
quizItService:
  user:
    name: user
    label: user-service
    containerName: user-service
    replicaCount: 1
    image:
      name: 712744100487.dkr.ecr.ap-northeast-2.amazonaws.com/user-service
      tag: |
        02ad45d7d52dd6406950394b0d0869f67b85bea4
    service:
      name: user-service
      label: user-service
    db:
      replicaCount: 1
      label: user-db
      storage:
        request: 1Gi
      service:
        name: user-db-svc
    apiPrefix: /api/user
  quiz:
    name: quiz
    label: quiz-service
    containerName: quiz-service
    replicaCount: 1
    image:
      name: 712744100487.dkr.ecr.ap-northeast-2.amazonaws.com/quiz-service
      tag: |
        8aa54a7eacf9dea0935fd4f50b6d4ca6cfe04b1e
    service:
      name: quiz-service
      label: quiz-service
    db:
      replicaCount: 1
      label: quiz-db
      storage:
        request: 10Gi
      service:
        name: quiz-db-svc
    apiPrefix: /api/quiz
  auth:
    name: auth
    label: auth-service
    containerName: auth-service
    replicaCount: 1
    image:
      name: 712744100487.dkr.ecr.ap-northeast-2.amazonaws.com/auth-service
      tag: |
        4cc3d19dc72f65c7f84a84388f66cd5085d9fa67
    service:
      name: auth-service
      label: auth-service
    db:
      replicaCount: 1
      label: auth-db
      requestCpu: 0.1
      configMap:
        name: redis-config
      service:
        name: auth-db-svc
    apiPrefix: /api/auth
  swagger:
    name: swagger
    label: swagger-ui
    containerName: swagger-ui
    replicaCount: 1
    service:
      name: swagger-ui
      label: swagger-ui
  front:
    name: front
    label: front-service
    containerName: front-service
    replicaCount: 1
    image:
      name: 712744100487.dkr.ecr.ap-northeast-2.amazonaws.com/front-service
      tag: |
        bbddbd2a8e4627c1f3680a9d4c44979845bec33c
    service:
      name: front-service
      label: front-service
  db:
    name: db
storage:
  provisioner: kubernetes.io/aws-ebs
  className: mongo-gp3
  type: gp3
  reclaimPolicy: Delete
  accessMode: ReadWriteOnce
ingress:
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:712744100487:certificate/8c25da53-7ba2-44f7-8c1c-e454de897be8
    alb.ingress.kubernetes.io/ssl-redirect: "443"
readinessProbe: /actuator/health/readiness
livenessProbe: /actuator/health/liveness
