# Default dev-values for quizit.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: prod
quizItService:
  user:
    name: user
    label: user-service
    containerName: user-service
    replicaCount: 1
    image:
      name: 712744100487.dkr.ecr.ap-northeast-2.amazonaws.com/user-service
      tag: |
        9bfd2397d4e44de18788244b5a698b0e4be666c5
    service:
      name: user-service
      label: user-service
    db:
      replicaCount: 1
      label: user-db
      storage:
        request: 1Gi
      service:
        name: user-db-svc
    apiPrefix: /api/user
  quiz:
    name: quiz
    label: quiz-service
    containerName: quiz-service
    replicaCount: 1
    image:
      name: 712744100487.dkr.ecr.ap-northeast-2.amazonaws.com/quiz-service
      tag: |
        17c4393f16028be5ddedb772ee9ff7e100b45630
    service:
      name: quiz-service
      label: quiz-service
    db:
      replicaCount: 1
      label: quiz-db
      storage:
        request: 10Gi
      service:
        name: quiz-db-svc
    apiPrefix: /api/quiz
  auth:
    name: auth
    label: auth-service
    containerName: auth-service
    replicaCount: 1
    image:
      name: 712744100487.dkr.ecr.ap-northeast-2.amazonaws.com/auth-service
      tag: |
        6d5dbbc36ca5b8b83ff7b76684015c7f192f6bde
    service:
      name: auth-service
      label: auth-service
    db:
      replicaCount: 1
      label: auth-db
      requestCpu: 0.1
      configMap:
        name: redis-config
      service:
        name: auth-db-svc
    apiPrefix: /api/auth
  front:
    name: front
    label: front-service
    containerName: front-service 
    replicaCount: 1
    image:
      name: 712744100487.dkr.ecr.ap-northeast-2.amazonaws.com/front-service
      tag: |
        7c0562f25f788aab220483cd0e69ab58487cbf1d
    service:
      name: front-service
      label: front-service
  db:
    name: db
storage:
  provisioner: kubernetes.io/aws-ebs
  className: mongo-gp3
  type: gp3
  reclaimPolicy: Delete
  accessMode: ReadWriteOnce
ingress:
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:712744100487:certificate/8c25da53-7ba2-44f7-8c1c-e454de897be8
    alb.ingress.kubernetes.io/ssl-redirect: "443"
readinessProbe: /actuator/health/readiness
livenessProbe: /actuator/health/liveness
