apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}-{{.Values.quizItService.user.name}}-deploy
spec:
  selector:
    matchLabels:
      app: {{.Values.quizItService.user.label}}
  replicas: {{ .Values.quizItService.user.replicaCount }}
  template:
    metadata:
      labels:
        app: {{.Values.quizItService.user.label}}
    spec:
      containers:
      - image: {{.Values.quizItService.user.image.name}}:{{.Values.quizItService.user.image.tag}}
        imagePullPolicy: Always
        name: {{.Values.quizItService.user.containerName}}
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: {{.Values.quizItService.user.apiPrefix}}{{.Values.livenessProbe}}
            port: 8080
        readinessProbe:
          httpGet:
            path: {{.Values.quizItService.user.apiPrefix}}{{.Values.readinessProbe}}
            port: 8080
        envFrom:
        - secretRef:
            name: quizit-secret-{{.Values.env}}
